@baseUrl = http://localhost:3000

#### create user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "email": "admin@coffeehub.com",
    "password": "admin",
    "name": "Admin",
    "isActive": true,
    "role": "admin"
}